baseURL = "https://meshstudio.io/"
languageCode = "en-us"
title = "Mesh Studio"

[params]
    googleAnalyticsUserID = "UA-90144908-1"
    rainImg = "/images/site/rain.svg"
    logoBlack = "/images/site/meshlogo-black-vector.svg"
    logoWhite = "/images/site/meshlogo-white-vector.svg"

# Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/work"
    weight = 5
[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
[[menu.main]]
    name = "Join Us"
    url = "/careers"
    weight = 5
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 5