baseURL = "https://meshstudio.io/"
languageCode = "en-us"
title = "Mesh Studio"

[params]
    googleAnalyticsUserID = "UA-90144908-1"
    logoBlack = "/images/mesh-logo-black.png"
    logoWhite = "/images/mesh-logo-white.png"

# Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/work"
    weight = 2
[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
[[menu.main]]
    name = "Join Us"
    url = "/careers"
    weight = 5
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 5