baseURL = "https://meshhq.github.io/"
languageCode = "en-us"
title = "Mesh Studio"
publishDir = "docs"

[params]
    googleAnalyticsUserID = "UA-90144908-1"
    rainImg = "/images/site/rain.svg"
    logoBlack = "/images/site/meshlogo-black-vector.svg"
    logoWhite = "/images/site/meshlogo-white-vector.svg"
    get_in_touch_title = "Ready to get started"
    get_in_touch_content = "Let's talk about your project"


# Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 1
[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Join Us"
    url = "/careers/"
    weight = 5
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 6